### ISSUE TITLE
Dataset property.

### ISSUE THREAD

**Issue by chekit** [UltimateAngular/redux-store#2]
https://github.com/UltimateAngular/redux-store/blob/9109ef8fd4b0639008975682fc4e7be33b275a1f/src/app.ts#L39

Why don't to use a [dataset](https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/dataset) property of HTMLElement instead of *getAttribute*?

```
const payload = JSON.parse(target.dataset.todo as any);
```

**Comment by toddmotto** [comment]
Either's fine, really.
